
platform :ios, '11.0'
# 引用框架
use_frameworks!
inhibit_all_warnings!

target 'confuse_test_swift' do
  
pod 'lottie-ios'
#  pod 'SnapKit'
 
end

# Workaround for Cocoapods issue #7606
#post_install do |installer|
#    installer.pods_project.build_configurations.each do |config|
#        config.build_settings.delete('CODE_SIGNING_ALLOWED')
#        config.build_settings.delete('CODE_SIGNING_REQUIRED')
#    end
#end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['SWIFT_VERSION'] = '4.2'
#    end
#  end
#end
